### ISSUE TITLE
Tests run in alphabetical order rather than declaration order

### ISSUE THREAD

**Issue by jesselawson** [jesselawson/tasty#5]
I remember reading that the Toml crate provides the `toml::Value`s in lexicographic (alphabetical) order. We can probably change this but it's not really an issue for me atm.

**Comment by jesselawson** [comment]
I take that back. It *is* an issue, centered around me forgetting something important about how the `toml` crate deserializes TOML data into a `Table` type. 

# What is going on?

Test cases are currently executed in an arbitrary order determined by the `toml` crate's internal `HashMap` behavior, rather than the order they're defined in the TOML file.

# Why does this matter?

This can cause problems when testing APIs where test order matters. For example, when one test creates a resource that subsequent tests depend on, or when tracking the progress of a multi-step workflow. 

# Why is this happening? 

I believe this issue has to do with how TOML data is parsed. The `toml` crate deserializes TOML into a `Table` type, which is essentially a wrapper around a `BTreeMap<String, Value>`. While `BTreeMap` does provide sorted keys, they're sorted alphabetically rather than in declaration order.

For example, let's say we have a test file like this:

```toml
[create_user]
method = "POST"
route = "api/users"
payload = { username = "testuser", email = "test@example.com" }
expect_http_status = 201
expect_response_includes = { success = true }

[get_user]
method = "GET"
route = "api/users/testuser"
payload = {}
expect_http_status = 200
expect_response_includes = { username = "testuser" }

[update_user]
method = "PATCH"
route = "api/users/testuser"
payload = { email = "updated@example.com" }
expect_http_status = 200
expect_response_includes = { email = "updated@example.com" }

[delete_user]
method = "DELETE"
route = "api/users/testuser"
payload = {}
expect_http_status = 204
```

The current implementation (`v0.9.4`) would run these tests in alphabetical order:
1. create_user
2. delete_user
3. get_user
4. update_user

This breaks the logical flow of what's going on, since the tests would try to delete a user before the user is retrieved or updated. In other words, the tests would fail because they're not executed in the intended order. 

# What can we do? 

Since we want to maintain the existing TOML test file format with table keys, we need to extract the order information before the TOML parser touches it. To do that, I suggest a function that scans the raw TOML content to extract table keys in the order they appear, then uses that ordered list to drive test execution. (The TOML parser would still be used to parse the actual test data).

I put [this Rust playground example](https://play.rust-lang.org/?version=stable&mode=debug&edition=2024&gist=2a1c43016fd6e0ece6e4f93a31d28a64) together. Code snippet below:

```rust
fn extract_table_keys_order(content: &str) -> Vec<String> {
    let mut keys = Vec::new();
    for line in content.lines() {
        let trimmed = line.trim();
        if trimmed.starts_with('[') // Should start with a '['
            && trimmed.ends_with(']') // Should end with a ']'
            && !trimmed[1..].contains('[') // Should not have s second '[' after pos 0
        {
            let key = trimmed[1..trimmed.len() - 1].to_string();
            keys.push(key);
        }
    }
    
    keys
}

fn main() {

    let toml_raw = r#"
[bad_email]
method = "POST"
route = "auth/signup"
payload.email = "chocolate"
payload.password = "doesnt matter; invalid email"
expect_http_status = 400
expect_response_includes.reason = "invalid_email"

[a_missing_password]
method = "POST"
route = "auth/login"
payload.email = "asdf@asdfasdf.com"
expect_http_status = 400
expect_response_includes.reason = "invalid_password"
    "#;
    
    for key in extract_table_keys_order(&toml_raw) {
        println!("{}", key);
    }
}
```

With something like this in place, we can modify `run_tests` to use this ordering instead:

```rust
// Here's how we do it now:
for (test_name, case) in test_cases {
    // Run test logic
}

// Here's how we would do it with a function that extracts the table keys in order
let ordered_keys = extract_table_keys_order(&content);
for key in ordered_keys {
    if let Some(case) = test_cases.get(&key) {
        // Run test...
    }
}
```

This ensures tests are run in the order they're defined in the test files while maintaining compatibility with the existing test file format. (I personally prefer to have the table keys as the test names).
